apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: sample-app
  name: sample-app
  namespace: sample-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io/v1
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: sample-app

